### ISSUE TITLE
Will argon update itself / pacaur?

### ISSUE THREAD

**Issue by still-dreaming-1** [14mRh4X0r/arch-argon#2]
I realize argon is just a GUI for pacaur, but my question still stands. Originally I installed an AUR package manually from the terminal. Then I followed that same process to install yaourt. Then I learned it is better to use pacaur instead of yaourt, so I used yaourt to install pacaur. Then I learned of the argon GUI for pacaur, so I used pacaur to install argon. Now I am using the argon GUI to keep everything up to date, but I'm not sure what would happen if a new version of argon and/or pacaur was released and I did a system update from inside argon.

**Comment by 14mRh4X0r** [comment]
As with pacman, everything will be updated, including pacaur and argon. The new version will be used next time you start them.
