### ISSUE TITLE
Launch Issue - GTK version

### ISSUE THREAD

**Issue by sokol99** [14mRh4X0r/arch-argon#5]
Hi, I am new to arch and have started installing aur packages.  I installed all the dependencies for argon via the get links in AUR.  However argon fails to launch and returns the following:

[user@arch ~]$ argon
/usr/bin/argon:3: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Vte, Gdk

I am using cinnamon for my UI.

Ideas?

Thanks, sokol99

**Comment by 14mRh4X0r** [comment]
Fixed in 3a1a639, will be released as 2.1.0

**Comment by sokol99** [comment]
Thank you!
